# Generated by Django 5.0.13 on 2025-03-16 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('filled_amount', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_hub.cryptocurrency')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_order_source', to='trading_hub.wallet')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limit_order_destination', to='trading_hub.wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
